services:
  - type: web
    name: news-app-api
    env: node
    buildCommand: ./deploy-without-vite.sh
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: news-db
          property: connectionString

databases:
  - name: news-db
    plan: free
